[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "mittschema"
version = "0.1.3"
description = "Weekly visual schedule with school integration"
license = "GPL-3.0-or-later"

[tool.setuptools.packages.find]
where = ["."]
